In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel('data.xlsx')
data

客户次类别  房产数  每房人数  平均年龄  客户主类别  罗马天主教比例  新教比例  其它宗教比例  无宗教比例  已婚占比  ...  \
0        33    1     3     2      8        0     5       1      3     7  ...   
1        37    1     2     2      8        1     4       1      4     6  ...   
2        37    1     2     2      8        0     4       2      4     3  ...   
3         9    1     3     3      3        2     3       2      4     5  ...   
4        40    1     4     2     10        1     4       1      4     7  ...   
...     ...  ...   ...   ...    ...      ...   ...     ...    ...   ...  ...   
5817     36    1     1     2      8        0     6       1      2     1  ...   
5818     35    1     4     4      8        1     4       1      4     6  ...   
5819     33    1     3     4      8        0     6       0      3     5  ...   
5820     34    1     3     2      8        0     7       0      2     7  ...   
5821     33    1     3     3      8        0     6       1      2     7  ...   

      投保个人意外险数量  投保家庭意外险数量  投保身残险数量  投保火险数量  投保冲浪险数量  投保船险数量  投保自行车险数量  \
0             0          0        0       1        0       0         0   
1             0          0        0       1        0       0         0   
2             0          0        0       1        0       0         0   
3             0          0        0       1        0       0         0   
4             0          0        0       1        0       0         0   
...         ...        ...      ...     ...      ...     ...       ...   
5817          0          0        0       1        0       0         0   
5818          0          0        0       1        0       0         0   
5819          0          0        0       1        0       0         0   
5820          0          0        0       0        0       0         0   
5821          0          0        0       0        0       0         0   

      投保财产险数量  投保社会安全险数量  移动房车险数量  
0           0          0        0  
1           0          0        0  
2           0          0        0  
3           0          0        0  
4           0          0        0  
...       ...        ...      ...  
5817        0          0        0  
5818        0          0        0  
5819        0          0        1  
5820        0          0        0  
5821        0          0        0  

[5822 rows x 86 columns]

In [4]:
data.iloc[:,85]

0       0
1       0
2       0
3       0
4       0
       ..
5817    0
5818    0
5819    1
5820    0
5821    0
Name: 移动房车险数量, Length: 5822, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_label,test_label = train_test_split(data.iloc[:,:85],data.iloc[:,85],test_size=0.15)

In [6]:
train_data

客户次类别  房产数  每房人数  平均年龄  客户主类别  罗马天主教比例  新教比例  其它宗教比例  无宗教比例  已婚占比  ...  \
2173     31    1     2     3      7        0     2       0      7     5  ...   
3637     22    1     2     2      5        0     4       1      5     4  ...   
4454     32    1     2     4      7        1     3       3      3     5  ...   
102      33    1     4     2      8        0     8       1      0     9  ...   
4925     23    1     2     2      5        0     6       2      2     4  ...   
...     ...  ...   ...   ...    ...      ...   ...     ...    ...   ...  ...   
2663     11    1     3     3      3        0     8       0      1     9  ...   
1769     35    1     2     4      8        2     5       1      2     8  ...   
5457     23    1     1     3      5        1     6       1      3     2  ...   
3708     33    1     3     3      8        1     5       0      3     7  ...   
573      23    1     1     4      5        2     2       2      4     0  ...   

      投保寿险数量  投保个人意外险数量  投保家庭意外险数量  投保身残险数量  投保火险数量  投保冲浪险数量  投保船险数量  \
2173       0          0          0        0       0        0       0   
3637       0          0          0        0       1        0       0   
4454       0          0          0        0       0        0       0   
102        0          0          0        0       1        0       0   
4925       0          0          0        0       1        0       0   
...      ...        ...        ...      ...     ...      ...     ...   
2663       0          0          0        0       1        0       0   
1769       0          0          0        0       0        0       0   
5457       0          0          0        0       1        0       0   
3708       0          0          0        0       0        0       0   
573        0          1          0        0       1        0       0   

      投保自行车险数量  投保财产险数量  投保社会安全险数量  
2173         0        0          0  
3637         0        0          0  
4454         0        0          0  
102          0        0          0  
4925         0        0          0  
...        ...      ...        ...  
2663         0        0          0  
1769         0        0          0  
5457         0        0          0  
3708         1        0          0  
573          0        0          0  

[4948 rows x 85 columns]

In [7]:
train_label

2173    0
3637    0
4454    0
102     0
4925    0
       ..
2663    0
1769    0
5457    0
3708    0
573     0
Name: 移动房车险数量, Length: 4948, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(train_data)
train_data_std = sc.transform(train_data)
test_data_std = sc.transform(test_data)
train_data_std
test_data_std

array([[ 0.67984321, -0.27576229, -0.8567318 , ..., -0.15128677,
        -0.08808436, -0.12065708],
       [-1.03868575, -0.27576229, -0.8567318 , ..., -0.15128677,
        -0.08808436, -0.12065708],
       [ 0.05492359,  2.24636674, -2.11874696, ..., -0.15128677,
        -0.08808436, -0.12065708],
       ...,
       [-1.66360537, -0.27576229,  0.40528337, ..., -0.15128677,
        -0.08808436, -0.12065708],
       [-1.27303061, -0.27576229,  0.40528337, ..., -0.15128677,
        -0.08808436, -0.12065708],
       [-0.25753622, -0.27576229,  0.40528337, ..., -0.15128677,
        -0.08808436, -0.12065708]])

In [19]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression(max_iter=500)
logreg.fit(train_data_std,train_label)

LogisticRegression(max_iter=500)

In [20]:
prepro = logreg.predict_proba(test_data_std)
acc = logreg.score(test_data_std,test_label)
acc

0.9336384439359268

In [21]:
prepro

array([[0.97982667, 0.02017333],
       [0.98933034, 0.01066966],
       [0.98544186, 0.01455814],
       ...,
       [0.06759586, 0.93240414],
       [0.96330327, 0.03669673],
       [0.96713228, 0.03286772]])

In [23]:
val = pd.read_excel('eval.xlsx')
val

客户次类别  房产数  每房人数  平均年龄  客户主类别  罗马天主教比例  新教比例  其它宗教比例  无宗教比例  已婚占比  ...  \
0        33    1     4     2      8        0     6       0      3     5  ...   
1         6    1     3     2      2        0     5       0      4     5  ...   
2        39    1     3     3      9        1     4       2      3     5  ...   
3         9    1     2     3      3        2     3       2      4     5  ...   
4        31    1     2     4      7        0     2       0      7     9  ...   
...     ...  ...   ...   ...    ...      ...   ...     ...    ...   ...  ...   
3995     33    1     2     4      8        0     7       2      0     5  ...   
3996     24    1     2     3      5        1     5       1      3     4  ...   
3997     36    1     2     3      8        1     5       1      3     7  ...   
3998     33    1     3     3      8        1     4       2      3     7  ...   
3999      8    1     2     3      2        4     3       0      3     5  ...   

      投保个人意外险数量  投保家庭意外险数量  投保身残险数量  投保火险数量  投保冲浪险数量  投保船险数量  投保自行车险数量  \
0             0          0        0       1        0       0         0   
1             0          0        0       1        0       0         0   
2             0          0        0       1        0       0         0   
3             0          0        0       1        0       0         0   
4             0          0        0       1        0       0         0   
...         ...        ...      ...     ...      ...     ...       ...   
3995          0          0        0       1        0       0         0   
3996          0          0        0       1        0       0         0   
3997          0          0        0       1        0       0         0   
3998          0          0        0       0        0       0         0   
3999          0          0        0       1        0       0         0   

      投保财产险数量  投保社会安全险数量  移动房车险数量  
0           0          0        0  
1           0          0        1  
2           0          0        0  
3           0          0        0  
4           0          0        0  
...       ...        ...      ...  
3995        0          0        0  
3996        0          0        1  
3997        1          0        0  
3998        0          0        0  
3999        0          0        0  

[4000 rows x 86 columns]

In [35]:
val_data = val.iloc[:,:85]
val_label = val.iloc[:,85]
val_data_std = sc.transform(val_data)
val_prepro = logreg.predict_proba(val_data_std)
test_acc = logreg.score(val_data_std,val_label)
test_acc

0.93875

In [36]:
val_prepro

array([[0.98573692, 0.01426308],
       [0.62361734, 0.37638266],
       [0.9312605 , 0.0687395 ],
       ...,
       [0.85567192, 0.14432808],
       [0.94337497, 0.05662503],
       [0.94528309, 0.05471691]])

In [37]:
import numpy as np
a = np.argmax(val_prepro,axis=1)
a

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
(val_label == a).sum()

3755

In [40]:
3755/4000

0.93875